### ISSUE TITLE
Option to disable script

### ISSUE THREAD

**Issue by Antonio-Laguna** [gfscott/eleventy-plugin-embed-twitter#16]
Hi @gfscott !

Great plugin here.

I was wondering if you'd be open for a PR that adds three options.

* Theme: There's no way to change the theme for tweets.
* Enabling `dnt`. I think in a privacy world it's great to have DNT enabled by default.
* Completely disabling the script. I want to build a dark theme switcher and I realised that I'd need to tinker the tweets with JS before the file is injected so I was planning on doing that on my own and realised I can't disable the JS.

I've seen you have an unmerged PR so I'm not sure if you're maintaining this! If you're not let me know too!

**Comment by gfscott** [comment]
Hey @Antonio-Laguna, thanks for filing an issue! Yes, absolutely, all three ideas sound good to me. Do you want to create that PR? Do you need any help from me other than reviewing? Happy to collaborate however you'd like.

Ha, I totally forgot about my unmerged PR — after I made it I wanted to sleep on it, and then...just forgot to merge it 😅 But forgetful or not, I'm still maintaining!

**Comment by Antonio-Laguna** [comment]
Thanks for getting back @gfscott !

I can do that PR I just wanted to check with you to double-check you were cool with that idea before jumping into code! Should I base off #13 so tests are kept at 100%?

Thanks again!
