### ISSUE TITLE
Option to center tweet and hide cards/conversations

### ISSUE THREAD

**Issue by felipeqq2** [gfscott/eleventy-plugin-embed-twitter#19]
Hey! I'd love to see some other options to customize the embed, in addition to #17! According to [Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference), there are options to define the alignment and hide cards or conversations with attributes at the `blockquote` element, just like `data-theme` and `data-dnt`.

Btw, I really appreciate the embed-everything plugins - it helps me a lot!

**Comment by gfscott** [comment]
Hey @felipeqq2 — yep, I think that should be quite doable. I was expecting to add additional `data-*` options sooner or later — a request makes it easy to prioritize!

**Comment by gfscott** [comment]
Shipped in [v1.3.0](https://github.com/gfscott/eleventy-plugin-embed-twitter/releases/tag/v1.3.0).
